### ISSUE TITLE
Package path ./styles.css is not exported from package

### ISSUE THREAD

**Issue by rodolphoasb** [transitive-bullshit/react-static-tweets#20]
Hi!

I'm using the latest version of this package. I've installed and put `import 'react-static-tweets/styles.css'` under `_app.js` but when I try to run `npm run dev` I've got the following error:

Module not found: Package path ./styles.css is not exported from package /home/rodolphoasb/Development/EpicThreads/frontend/node_modules/react-static-tweets (see exports field in /home/rodolphoasb/Development/EpicThreads/frontend/node_modules/react-static-tweets/package.json)

The exported files in package.json are:

{
  "name": "react-static-tweets",
  "version": "0.4.0",
  "description": "Extremely fast static renderer for tweets.",
  "repository": "transitive-bullshit/react-static-tweets",
  "author": "Travis Fischer <travis@transitivebullsh.it>",
  "license": "MIT",
  "main": "build/cjs/index.js",
  "module": "build/esm/index.js",
  "typings": "build/esm/index.d.ts",
  "type": "commonjs",
  "sideEffects": [
    "*.css"
  ],
  "exports": {
    "import": "./build/esm/index.js",
    "default": "./build/cjs/index.js"
  },
  "engines": {
    "node": ">=12"
  },
  "dependencies": {
    "classnames": "^2.2.6",
    "styled-jsx": "^3.4.2",
    "swr": "^0.4.2"
  },
  "devDependencies": {
    "@types/react": "^17.0.1",
    "@types/react-dom": "^17.0.0",
    "date-fns": "^2.17.0",
    "next": "^10.0.6",
    "react": "^17.0.1",
    "react-dom": "^17.0.1"
  },
  "peerDependencies": {
    "date-fns": ">=2",
    "next": "^10.0.6",
    "react": ">=16",
    "react-dom": ">=16"
  },
  "gitHead": "fc97352e6421cad49d2ca2a161ba3ef6301d8406"
}

**Comment by transitive-bullshit** [comment]
Thanks @rodolphoasb; this is due to webpack 5 being more strict.

Should be fixed in `0.5.0` if you upgrade. https://github.com/transitive-bullshit/react-static-tweets/commit/66824536a26ade4536182043b2def051f4f7aeb6
