### ISSUE TITLE
React static tweets is throwing CORS error.

### ISSUE THREAD

**Issue by jaisharx** [transitive-bullshit/react-static-tweets#31]
![image](https://user-images.githubusercontent.com/55892116/120266456-90dee180-c2bf-11eb-8db5-557283a559d8.png)

**Comment by spetrey** [comment]
This is a huge error. Looks like the problem is here:
https://github.com/transitive-bullshit/react-static-tweets/blob/master/packages/react-static-tweets/src/twitter.tsx#L30

**Comment by spetrey** [comment]
Wow, from the README of twitter-seach:

> NOTE: The hosted version of Twitter Search has unfortunately been disabled due to abuse and excessive Algolia costs.

**Comment by spetrey** [comment]
I wonder if this fetch url can simply be refactored to: `https://syndication.twitter.com/tweets.json?ids=${id}`? I'm not entirely sure what kind of data `https://twitter-search.vercel.app/api/get-tweet-ast/${id}` returned

**Comment by transitive-bullshit** [comment]
The issue is that my personal Vercel account was disabled due to switching from their legacy plan to a new hobby plan. Apparently some of the usage exceeded Vercel's thresholds even though I only use it for free & open source demos (along with hosting my personal blog).

This is not an issue with `react-static-tweets`. It is only an issue with the demo and my personal Vercel account.

I'll update this issue once I hear back from Vercel's support team (since they don't allow you to just pay to upgrade personal accounts).

**Comment by spetrey** [comment]
Looks like some static tweets are starting to come back:

https://twitter-search.vercel.app/api/get-tweet-ast/1399843866291978259

**Comment by jaisharx** [comment]
I think the recommend way of using this package should be self hosted. ```react-static-tweet``` can export a simple api handler function that developers can just import in their next.js API route. Somewhat like this. 👇

 ```js

import { fetchTweetAst } from 'static-tweets'

export default async function getTweetAstHandler(req, res) {
  const { id } = req.query
  const tweetAst = await fetchTweetAst(id)

  res.status(200).json({ tweetAst })
}

```

and instead of the package using this hardcoded url "`https://twitter-search.vercel.app/api/get-tweet-ast/${id}`", it can just point to a relative next.js endpoint '/api/get-ast', which exports the above function.

Switching to self hosted would not require lot of changes, while it would make the package future proof for any such failures. [Covid.army](http://covid.army/) was using this package for rendering tweets, and when things broke, our complete functionality was down, I temporary switched to another package, but they were just slow (ofc).

**Comment by transitive-bullshit** [comment]
@jaisharx this is already possible. Just override the default fetcher option to `TwitterContextProvider`:

```ts
    <TwitterContextProvider
      value={{
        tweetAstMap: (recordMap as any).tweetAstMap || {},
        swrOptions: {
          fetcher: (id) =>
            fetch(`/api/get-tweet-ast/${id}`).then((r) => r.json())
        }
      }}
    >
      // ...
    </TwitterContextProvider>
 ```

We could make this the default, but then the default wouldn't work for everyone out of the box.

**Comment by transitive-bullshit** [comment]
The default behavior should be to fetch the tweet ASTs server-side as in our example: https://github.com/transitive-bullshit/react-static-tweets/blob/master/example/pages/index.tsx#L7-L9

The client-side fetching is provided as a convenient fallback, but unless you're relying on your own endpoint, I wouldn't rely on it in production.

If anyone wants to update the docs to better reflect this tradeoff, that'd be awesome.

Thanks :)
