### ISSUE TITLE
Expose ability to override partial context

### ISSUE THREAD

**Issue by transitive-bullshit** [transitive-bullshit/react-static-tweets#4]
see https://github.com/transitive-bullshit/react-static-tweets/blob/master/packages/react-static-tweets/src/twitter.ts

**Comment by DaniGuardiola** [comment]
Working on this, will link PR soon.

**Comment by DaniGuardiola** [comment]
Do we want deep or shallow merge? @transitive-bullshit

**Comment by transitive-bullshit** [comment]
@DaniGuardiola take a look at what I'm doing here.. it's a mixture of both https://github.com/NotionX/react-notion-x/blob/master/packages/react-notion-x/src/context.tsx#L126

**Comment by DaniGuardiola** [comment]
@transitive-bullshit please close :)

**Comment by transitive-bullshit** [comment]
Thanks, @DaniGuardiola 🙏
